import { auth, db } from '../firebase/firebase-config.js';
import { signInWithEmailAndPassword, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { collection, query, where, getDocs, limit } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const form=document.getElementById('studentLoginForm'),idInput=document.getElementById('studentId'),pass=document.getElementById('password'),btn=document.getElementById('loginBtn'),msg=document.getElementById('loginMessage');
const emailFor=id=>String(id||'').trim().toUpperCase().replace(/\s+/g,'')+'@students.sshacms.local';
const show=(t,type='error')=>{if(msg){msg.textContent=t;msg.className='message show '+type}};
async function findStudent(uid){const snap=await getDocs(query(collection(db,'students'),where('uid','==',uid),limit(1)));if(snap.empty)return null;const s=snap.docs[0];return s.data().loginEnabled===true?s:null;}
onAuthStateChanged(auth,async user=>{if(!user)return;try{const s=await findStudent(user.uid);if(s){const d=s.data();localStorage.setItem('studentDocId',s.id);localStorage.setItem('studentId',d.studentId||'');localStorage.setItem('studentName',d.name||'');localStorage.setItem('studentUid',user.uid);location.replace('student-dashboard.html')}else await signOut(auth)}catch(e){console.error(e)}});
form?.addEventListener('submit',async e=>{e.preventDefault();const sid=idInput.value.trim().toUpperCase(),pw=pass.value;if(!sid||!pw)return show('Please enter Student ID and password.');btn.disabled=true;btn.textContent='Signing in...';try{const cred=await signInWithEmailAndPassword(auth,emailFor(sid),pw);const s=await findStudent(cred.user.uid);if(!s||String(s.data().studentId||'').trim().toUpperCase()!==sid)throw new Error('Student account is not linked correctly.');const d=s.data();localStorage.setItem('studentDocId',s.id);localStorage.setItem('studentId',d.studentId||'');localStorage.setItem('studentName',d.name||'');localStorage.setItem('studentUid',cred.user.uid);show('Login successful. Opening Student Portal...','success');setTimeout(()=>location.replace('student-dashboard.html'),300)}catch(e){console.error(e);show(e?.code==='auth/too-many-requests'?'Too many attempts. Please try again later.':'Student ID or password is incorrect.');btn.disabled=false;btn.textContent='Login to Student Portal'}});
